# Generated by Django 4.2.7 on 2026-04-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('total', models.IntegerField(default=1, verbose_name='总库存')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=200, verbose_name='书名（快照）')),
                ('borrow_date', models.DateField(verbose_name='借出日期')),
                ('due_date', models.DateField(verbose_name='应还日期')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='归还日期')),
                ('status', models.CharField(choices=[('borrowing', '借出中'), ('overdue', '逾期'), ('returned', '已归还')], max_length=10, verbose_name='状态')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='borrows.book', verbose_name='书籍')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'db_table': 'borrows',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
