# Generated by Django 4.2.7 on 2026-04-11 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='讲座主题')),
                ('activity_type', models.CharField(choices=[('reading_club', '读书会'), ('english_corner', '英语角'), ('lecture', '讲座')], default='lecture', max_length=20, verbose_name='活动类型')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用')),
                ('status', models.CharField(choices=[('upcoming', '即将开始'), ('ongoing', '进行中'), ('finished', '已结束')], default='upcoming', max_length=10, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'activities',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityParticipation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际支付金额')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='activities.activity', verbose_name='活动')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_participations', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_participations', to='members.member', verbose_name='会员')),
            ],
            options={
                'verbose_name': '活动参与记录',
                'verbose_name_plural': '活动参与记录',
                'db_table': 'activity_participations',
                'ordering': ['-registered_at'],
                'unique_together': {('member', 'activity')},
            },
        ),
    ]
