# Generated by Django 4.2.7 on 2026-04-11 11:35

from django.db import migrations, models
import django.db.models.deletion


def create_default_activity_types(apps, schema_editor):
    """创建默认的活动类型"""
    ActivityType = apps.get_model('activities', 'ActivityType')

    default_types = [
        {'name': '读书会', 'code': 'reading_club', 'color': '#67c23a', 'description': '读书分享活动'},
        {'name': '英语角', 'code': 'english_corner', 'color': '#e6a23c', 'description': '英语交流练习'},
        {'name': '讲座', 'code': 'lecture', 'color': '#f56c6c', 'description': '专题讲座'},
    ]

    for type_data in default_types:
        ActivityType.objects.create(**type_data)


def migrate_activity_data(apps, schema_editor):
    """迁移现有活动的活动类型数据"""
    Activity = apps.get_model('activities', 'Activity')
    ActivityType = apps.get_model('activities', 'ActivityType')

    # 保存旧的活动类型值
    for activity in Activity.objects.all():
        # 从临时列获取旧的活动类型值
        old_type = getattr(activity, '_old_activity_type', None)
        if old_type:
            try:
                activity_type = ActivityType.objects.get(code=old_type)
                activity.activity_type = activity_type
                activity.save()
            except ActivityType.DoesNotExist:
                print(f"Warning: ActivityType with code '{old_type}' not found for activity {activity.id}")


def reverse_migrate_activity_data(apps, schema_editor):
    """反向迁移"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='类型代码')),
                ('color', models.CharField(default='#409eff', max_length=20, verbose_name='显示颜色')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '活动类型',
                'verbose_name_plural': '活动类型',
                'db_table': 'activity_types',
                'ordering': ['id'],
            },
        ),
        # 先添加一个临时列来保存旧数据
        migrations.AddField(
            model_name='activity',
            name='_old_activity_type',
            field=models.CharField(max_length=20, null=True),
        ),
        # 将旧的活动类型数据复制到临时列
        migrations.RunSQL(
            "UPDATE activities SET _old_activity_type = activity_type WHERE activity_type IS NOT NULL",
            reverse_sql="UPDATE activities SET activity_type = _old_activity_type WHERE _old_activity_type IS NOT NULL"
        ),
        # 创建默认活动类型
        migrations.RunPython(create_default_activity_types, migrations.RunPython.noop),
        # 修改 activity_type 字段为外键
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='activities.activitytype', verbose_name='活动类型'),
        ),
        # 迁移数据
        migrations.RunPython(migrate_activity_data, reverse_migrate_activity_data),
        # 删除临时列
        migrations.RemoveField(
            model_name='activity',
            name='_old_activity_type',
        ),
    ]
