# Generated by Django 4.2.7 on 2026-05-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_add_activity_type_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.AddField(
            model_name='activity',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='支持jpg、jpeg、png、gif、webp等格式', null=True, upload_to='activity_covers/%Y/%m/', verbose_name='活动封面'),
        ),
    ]
