# Generated by Django 4.2.7 on 2026-05-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_location_activity_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('not_started', '未开始'), ('upcoming', '即将开始'), ('ongoing', '进行中'), ('finished', '已结束')], default='not_started', max_length=20, verbose_name='状态'),
        ),
    ]
